#!/usr/bin/env perl

use strict;
use warnings;
no warnings 'uninitialized';
use Getopt::Long;
use Benchmark;
use Carp;
use Data::Dumper;
use Scalar::Util qw(looks_like_number);
use File::Basename;

my ($file, $chr, $help);

GetOptions(
    'f|file=s'      =>  \$file,
    'c|chr=s'       =>  \$chr,
    'h|help'	    =>  \$help,
);

($file && $chr && !$help) or die <<USAGE;
    Usage: $0 -f snp_file -c chromosome 
USAGE

#~ Slice object:
  #~ coord_system:version:seq_region_name:start:end:strand
#~ For example:
  #~ chromosome:NCBIM37:X:1:10000:1

my $stub = 'chromosome:NCBI36:'.$chr.':';

open FL1, "<", $file;
open OUTF, ">", "/nfs/users/nfs_j/jm23/jm23/GWAS_genotypes_WGS/double_check/GWAS_genotypes_WGS/remapping_gtype/$file\_chr$chr\_data_for_remapping";
#open OUTF, ">", "/nfs/users/nfs_j/jm23/jm23/scratch/vcf_annotation/remapping/chr$chr\_coords_for_remapping";

while ( <FL1> ) {
	chomp;
    my @mapping = split("\t", $_);
    if ( $mapping[0] == $chr ) {
		print OUTF $stub.$mapping[1].':'.$mapping[1].":\n";
	}
}    

close OUTF;
close FL1;
