#!/usr/bin/env perl

use strict;
use warnings;
no warnings 'uninitialized';
use Getopt::Long;
use Benchmark;
use Carp;
use Data::Dumper;
use Scalar::Util qw(looks_like_number);
use File::Basename;

my ($file, $help);

GetOptions(
    'f|file=s'      =>  \$file,
    'h|help'	    =>  \$help,
);

($file && !$help) or die <<USAGE;
    Usage: $0 -f snp_file  
USAGE

system qq[echo 'perl /nfs/users/nfs_j/jm23/work/web/current/import_scripts/new_remapper/remapping_18_19_all -f $file ' | bsub -M8000000 -R'select[mem>8000] rusage[mem=8000]' -o $file\_remapping.out];
