#!/usr/bin/env perl

use strict;
use warnings;
no warnings 'uninitialized';
use Getopt::Long;
use Benchmark;
use Carp;
use Data::Dumper;
use Scalar::Util qw(looks_like_number);

my ($type, $help);

GetOptions(
    't|type=s'      =>  \$type,
    'h|help'	    =>  \$help,
);

($type && !$help) or die <<USAGE;
    Usage: $0 -t snp_or_indel 
USAGE


my @chr_arr = (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,'X');
for my $chr ( @chr_arr ) {
	system qq[echo 'perl /nfs/users/nfs_j/jm23/work/web/current/import_scripts/final_remapping -c $chr -t $type' | bsub -M8000000 -R'select[mem>8000] rusage[mem=8000]' -o final_remapping_37_$chr\_$type.out];
}
