#!/usr/bin/env perl

use strict;
use warnings;
no warnings 'uninitialized';
use Getopt::Long;
use Benchmark;
use Carp;
use Data::Dumper;
use Scalar::Util qw(looks_like_number);

my @chr_arr = (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,'X');
for my $chr ( @chr_arr ) {
	system qq[echo 'sort -k 2 -n /nfs/users/nfs_j/jm23/jm23/scratch/vcf_annotation/remapping/out_sub_indel_remap_$chr.txt > /nfs/users/nfs_j/jm23/jm23/scratch/vcf_annotation/remapping/out_sub_indel_sort_remap_$chr.txt' | bsub -M8000000 -R'select[mem>8000] rusage[mem=8000]' -o indel_sort_mapping_$chr.out];
}
